### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ducquyen2509** [zalopay-oss/docker-grpc-gateway#1]
Hi Anh,
Em đã làm theo hướng dẫn nhưng khi test lại bị lỗi 
curl: (7) Failed to connect to localhost port 8000: Connection refused

Nhờ anh support giúp ạ

**Comment by phamtai97** [comment]
Hi bạn.
Bạn có thể cho mình thêm thông tin:
- Bạn đã start docker service port 8000 lên chưa ( chụp anh xem cmd)
- Bạn đang test một service hay test nhiều service
- Comment các lệnh em chạy.

**Comment by ducquyen2509** [comment]
Hi anh,
Em đã thay port 8000 thành 9009
Em đã start cả 2 service rồi ạ (Như hình)
Em đang test nhiều service và run theo các lệnh anh note trong git.
![image](https://user-images.githubusercontent.com/12408803/59546924-08df6000-8f60-11e9-9fb4-762d19f11787.png)
Mong anh giúp đỡ

**Comment by Trung-DV** [comment]
@ducquyen2509 Trên Mac, `--network host` không hoạt động như trên Linux: [`The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.`](https://docs.docker.com/network/host/), do đó gateway forward request sang service (localhost:9009) sẽ không được. Bạn phải tạo 1 `docker network` cho gateway và service (để chúng có thể ping đến nhau). Sau đó sửa config(`config.yaml`) lại để gateway  forward request đến container đang chạy service ping (bằng ip của container hoặc tên của container).

Có thể theo step như sau:
- Bước 1:  Sửa file `config.yaml`:
 
 backend: "service-ping:9009" sau đó build lại gateway

- Bước 2:
```sh
$ docker network create grpc-network
$ docker run  --network grpc-network grpc-gateway
$ docker run  --network grpc-network service-ping
```

**Comment by ducquyen2509** [comment]
Hi Anh,
Em đã thử theo các bước anh hướng dẫn nhưng vẫn không được
https://gyazo.com/344680d796964993e52dff1178be3093

**Comment by Trung-DV** [comment]
@ducquyen2509  Sr bạn, mình quên mất, bạn phải publish port 9000:
```sh
docker run --network grpc-gw -p 9000:9000 grpc-gateway
```

**Comment by ducquyen2509** [comment]
Hi anh,
Hiện tại khi em test thì server báo lỗi 503 nhỉ?
{"@timestamp":"2019-06-15T10:41:42Z","duration":0,"host":"172.19.0.1","level":"info","method":"GET","msg":"GET /core/serviceA/ping/999999 503","referer":"","remote":"172.19.0.1:43054","request":"/core/serviceA/ping/999999","request_id":"","size":401,"status":503,"url":"/core/serviceA/ping/999999","user_agent":"curl/7.54.0"}

p/s: em không biết code golang, em đang làm 1 bài present java-grpc mà tới phần gateway thấy bài của anh nên thử download về test thử, nên mong anh giúp đỡ :D

**Comment by phamtai97** [comment]
Hi bạn.
Bạn thử publish:
```sh
docker run --network grpc-gw -p 9000:9000 grpc-gateway
docker run --network grpc-gw -p 9009:9009 service-ping
```

**Comment by phamtai97** [comment]
@ducquyen2509 bạn nhớ docker build lại gateway khi sửa file config nha. Và bạn đã sửa trong file Dockerfile EXPOSE 9009 chưa

**Comment by ducquyen2509** [comment]
Hi anh @phamtai97 ,
Em đã build lại và đã sửa port thành 9009 rồi. Cũng đã publish 9009 ở service

**Comment by Trung-DV** [comment]
@ducquyen2509 Theo như ảnh thì mình thấy gateway start trước service, có thể do đó nó không biết được `service-ping` là ip nào. Mình đã thử lại thì nếu start service-ping trước gateway thì chạy được, còn nếu gateway start sau thì nó bị lỗi 503 đó.

**Comment by ducquyen2509** [comment]
@dvt1996 Em đã thử start service-ping trước nhưng vẫn bị 503. :(

**Comment by thinhdanggroup** [comment]
Hi @ducquyen2509 

Để grpc-gateway, ta thêm option `--link` khi chạy `docker run` nha. Lưu ý: nhớ đặt tên cho service khi  `run` để dễ link hơn.

> docker run --name service-ping service-ping

![image](https://user-images.githubusercontent.com/26034284/59576011-19badd80-90e8-11e9-87f7-9753a96cdff0.png)

> docker run -p 9000:9000 --rm --name grpc-gateway --link service-ping grpc-gateway

![image](https://user-images.githubusercontent.com/26034284/59576017-22131880-90e8-11e9-86f8-3c884a57170b.png)

**Note**: kiểm tra grpc-gateway có kết nối với service-ping chưa?

![image](https://user-images.githubusercontent.com/26034284/59576080-8209bf00-90e8-11e9-9d0d-47365f02b484.png)

Kết quả:

![image](https://user-images.githubusercontent.com/26034284/59576035-3ce58d00-90e8-11e9-9caa-a9779a54258e.png)

**Comment by ducquyen2509** [comment]
@thinhdanggroup Dạ đã chạy được rồi ạ.
Cảm ơn các anh đã hỗ trợ.
Cho em hỏi phần gateway này mình làm bằng java được không anh nhỉ? em cũng có search trên google thì toàn thấy hướng dẫn bằng golang. Hiện tại nó chưa support bằng java hay sao anh nhỉ?

**Comment by phamtai97** [comment]
Hi bạn.
@ducquyen2509  đúng rồi ạ. Hiện tại Google chỉ mới hỗ trợ plugin grpc-gateway cho ngôn ngữ `Golang`. bạn có thể xem [tại đây](https://github.com/grpc-ecosystem/grpc-gateway).

Khi sử dụng grpc-gateway có thể làm `giảm performace` của hệ thống. Bạn nên cân nhắc khi sử dụng.

**Comment by ducquyen2509** [comment]
@phamtai97 Ok anh. Cảm ơn anh đã hỗ trợ.

**Comment by ducquyen2509** [comment]
Anh @phamtai97 
Anh cho em hỏi nếu gateway vẫn build bằng  golang nhưng service em chạy bằng java được không anh nhỉ?

**Comment by phamtai97** [comment]
Hi bạn.
@ducquyen2509 được chứ bạn. Trong demo mình chạy serviceA và servieB bằng Golang cho tiện. Chứ thực tế các grpc-service bạn dùng ngôn ngữ gì cũng được nhé.

Bạn chỉ cần có file proto của service đó, và làm theo như hướng dẫn trong bài [blog](https://medium.com/zalopay-engineering/buildingdocker-grpc-gateway-e2efbdcfe5c) là được.

**Comment by ducquyen2509** [comment]
Ok anh. Cảm ơn anh. để em làm thử.

**Comment by ducquyen2509** [comment]
Hi anh,
sau khi em run câu lệnh :
docker run -v `pwd`:/defs namely/gen-grpc-gateway -f . -s Greet
thì em có đọc trong bài thì nó sẽ tự động sinh ra theo như cấu trúc. Nhưng khi em run thì em thấy thiếu phần pkg. Các file config.yaml và Dockerfile là tự động sinh ra hay mình phải tạo ra vậy a?
![image](https://user-images.githubusercontent.com/12408803/59594581-4d185f00-911e-11e9-8b95-98053b58784e.png)

**Comment by phamtai97** [comment]
Hi bạn.
Bạn cho mình xem file Greet.proto với ạ

**Comment by ducquyen2509** [comment]
Hi anh,
Hồi nãy em config nhầm bên file proto, sửa xong thì nó sinh ra đầy đủ rồi nhưng khi build thì nó bị lỗi
src/pkg/main/main.go:256:9: undefined: Greet_proto.RegisterGreetHandlerFromEndpoint
- file proto ở java: 

syntax = "proto3";
option java_multiple_files = true;
option java_package = "zalopay.example.grpc";
message registerRequest {
    string username = 1;
}

message registerResponse {
    string username = 1;
    string token = 2;
}

service GreetService {
    rpc registerGreet (registerRequest) returns (registerResponse)
}

- file proto ở golang:

syntax = "proto3";
option java_multiple_files = true;
option go_package = "Greet.proto";
package zalopay.example.grpc;
import "google/api/annotations.proto";

message registerRequest {
    string username = 1;
}

message registerResponse {
    string username = 1;
    string token = 2;
}

service GreetService {
    rpc registerGreet (registerRequest) returns (registerResponse){
        option (google.api.http) = {
      get: "/v1/register/{username}"
    };
    }
}
Anh xem file proto ở golang em có sai chỗ package gì không a?

**Comment by phamtai97** [comment]
@ducquyen2509  bạn đặt tên service trong file proto là `GreetService ` thì lúc chạy cmd bạn phải dùng:

>docker run -v pwd:/defs namely/gen-grpc-gateway -f . -s GreetService

**Comment by ducquyen2509** [comment]
À, Cảm ơn anh @phamtai97 👍

**Comment by ducquyen2509** [comment]
Hi anh,
Hiện tại em build 1 con service bằng java và 1 con gateway.
Em đã thử ping từ gateway và con service thì được nhưng khi test thì nó báo không tìm thấy method
"error":"Method not found: zalopay.example.grpc.GreetService/registerGreet"

Em đã thử viết 1 client call bằng grpc bình thường thì thấy service đó hoạt động bình thường.

Em đang nghi ngờ file proto chỗ package nó có vấn đề chỗ nào đó. Anh xem giúp em với ạ
- File proto ở Service (JAVA):
syntax = "proto3";
option java_multiple_files = true;
option java_package = "zalopay.example.grpc";
message registerRequest {
    string username = 1;
}

message registerResponse {
    string username = 1;
    string token = 2;
}

service GreetService {
    rpc registerGreet (registerRequest) returns (registerResponse);
}

- FIle proto ở Gateway

syntax = "proto3";
option java_multiple_files = true;
package zalopay.example.grpc;
import "google/api/annotations.proto";

message registerRequest {
    string username = 1;
}

message registerResponse {
    string username = 1;
    string token = 2;
}

service GreetService {
    rpc registerGreet (registerRequest) returns (registerResponse){
        option (google.api.http) = {
      get: "/v1/register/{username}"
    };
    }
}
